#!/usr/bin/env bash
#
# corpus/lint.sh — health check for the Atrium corpus (see CLAUDE.md).
#
#   bash corpus/lint.sh          # check: frontmatter, links, page size; exit != 0 on failure
#   bash corpus/lint.sh --index  # regenerate the wiki catalog block in index.md
#
# Checks every wiki/*.md has `summary:` + `updated:` frontmatter, that every
# relative markdown link resolves on disk, and that no page's BODY (frontmatter
# excluded) exceeds ~200 lines. Mechanical only — the human sweep for stale
# claims / contradictions still lives in the skill's §7.
#
# One exemption to the link check: a link to SOURCE CODE from a brief in done/
# or superseded/ is warned about, not failed. Those briefs are immutable, so
# they cannot be updated when code moves — see the long note at the check.

set -uo pipefail

CORPUS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WIKI_DIR="$CORPUS_DIR/wiki"
INDEX="$CORPUS_DIR/index.md"
MAX_BODY_LINES=200

# --- helpers ----------------------------------------------------------------

# Print the frontmatter value for a key ("" if absent). Reads only the leading
# `---`…`---` block.
frontmatter_value() {
  awk -v key="$1:" '
    NR==1 && $0!="---" { exit }
    NR==1 { infm=1; next }
    infm && $0=="---" { exit }
    infm && index($0, key)==1 {
      sub("^" key "[ \t]*", ""); print; exit
    }
  ' "$2"
}

# Count body lines = total minus the leading frontmatter block (if any).
body_line_count() {
  awk '
    NR==1 && $0=="---" { infm=1; next }
    infm && $0=="---" { infm=0; next }
    infm { next }
    { n++ }
    END { print n+0 }
  ' "$1"
}

# --- --index: regenerate the wiki catalog block -----------------------------

if [[ "${1:-}" == "--index" ]]; then
  BEGIN="<!-- BEGIN wiki-catalog (generated by lint.sh --index) -->"
  END="<!-- END wiki-catalog -->"
  if ! grep -qF "$BEGIN" "$INDEX" || ! grep -qF "$END" "$INDEX"; then
    echo "lint: index.md is missing the '$BEGIN' / '$END' markers; add them where the wiki catalog should go." >&2
    exit 1
  fi
  tmp="$(mktemp)"
  {
    echo "$BEGIN"
    for f in "$WIKI_DIR"/*.md; do
      base="$(basename "$f")"
      summary="$(frontmatter_value summary "$f")"
      [[ -z "$summary" ]] && summary="(no summary — add frontmatter)"
      echo "- [$base](wiki/$base) — $summary"
    done
    echo "$END"
  } > "$tmp"
  # Splice the generated block in place of the old one.
  awk -v beginm="$BEGIN" -v endm="$END" -v block="$tmp" '
    $0==beginm { inblk=1; while((getline line < block) > 0) print line; close(block); next }
    $0==endm { inblk=0; next }
    !inblk { print }
  ' "$INDEX" > "$INDEX.new" && mv "$INDEX.new" "$INDEX"
  rm -f "$tmp"
  echo "lint: regenerated wiki catalog in index.md ($(ls "$WIKI_DIR"/*.md | wc -l | tr -d ' ') pages)."
  exit 0
fi

# --- check mode -------------------------------------------------------------

fail=0
err() { echo "lint: $1" >&2; fail=1; }

# 1) Frontmatter + 2) body size, per wiki page.
for f in "$WIKI_DIR"/*.md; do
  rel="wiki/$(basename "$f")"
  [[ -z "$(frontmatter_value summary "$f")" ]] && err "$rel: missing 'summary:' frontmatter"
  [[ -z "$(frontmatter_value updated "$f")" ]] && err "$rel: missing 'updated:' frontmatter"
  n="$(body_line_count "$f")"
  (( n > MAX_BODY_LINES )) && err "$rel: body is $n lines (> $MAX_BODY_LINES) — split it (one concept per file)"
done

# 3) Relative links resolve, across the whole corpus.
#
# One exemption, and it exists because two of CLAUDE.md's rules would otherwise
# contradict each other: **briefs are immutable**, and **every relative link
# resolves**. A finished brief cites the code as it stood the day it shipped, so
# the first rename or refactor breaks a link in a file nobody is allowed to
# edit. Brief 52 (the api module/Knex restructure, 2026-08-30) broke 24 of them
# at once.
#
# So a link from `briefs/done/` or `briefs/superseded/` that points OUT of the
# corpus — i.e. at source code — is reported as a **stale** warning and does not
# fail the run. It is history, and history is allowed to name files that have
# since moved.
#
# Everything else still fails, deliberately:
#   - links *within* the corpus from any file (brief → brief, brief → wiki),
#     because those are navigation and a broken one strands a reader;
#   - every link from `wiki/`, because a wiki page describes the code as it is
#     now, and a stale path there is a false claim;
#   - every link from `briefs/todo/`, because a todo brief names the files it is
#     about to change and a wrong path is a wrong spec.
stale=0
while IFS= read -r f; do
  dir="$(dirname "$f")"
  # Historical briefs: code links may have rotted since they were written.
  historical=0
  case "$f" in
    "$CORPUS_DIR"/briefs/done/*|"$CORPUS_DIR"/briefs/superseded/*) historical=1 ;;
  esac
  # Pull every ](target) markdown link target.
  grep -oE '\]\([^)]+\)' "$f" 2>/dev/null | sed -E 's/^\]\(//; s/\)$//' | while IFS= read -r target; do
    # Skip URLs, mail, and pure in-page anchors.
    case "$target" in
      http://*|https://*|mailto:*|\#*) continue ;;
    esac
    path="${target%%#*}"          # strip #anchor
    [[ -z "$path" ]] && continue
    [[ -e "$dir/$path" ]] && continue
    # Does the target point outside the corpus (i.e. at source code)?
    resolved="$(cd "$dir" 2>/dev/null && printf '%s' "$(realpath -m "$path" 2>/dev/null)")"
    outside=1
    case "$resolved" in "$CORPUS_DIR"/*|"$CORPUS_DIR") outside=0 ;; esac
    if (( historical )) && (( outside )); then
      echo "lint: $(basename "$f"): stale code link (historical brief, not a failure) -> $target" >&2
      echo "STALE" >> "$CORPUS_DIR/.lint-stale"
    else
      echo "lint: $(basename "$f"): broken relative link -> $target" >&2
      echo "BROKEN" >> "$CORPUS_DIR/.lint-broken"
    fi
  done
done < <(find "$CORPUS_DIR" -name '*.md')

if [[ -f "$CORPUS_DIR/.lint-stale" ]]; then
  stale="$(wc -l < "$CORPUS_DIR/.lint-stale" | tr -d ' ')"
  rm -f "$CORPUS_DIR/.lint-stale"
fi

if [[ -f "$CORPUS_DIR/.lint-broken" ]]; then
  fail=1
  rm -f "$CORPUS_DIR/.lint-broken"
fi

if (( fail )); then
  echo "lint: FAILED" >&2
  exit 1
fi
if (( stale > 0 )); then
  echo "lint: OK — wiki frontmatter, link resolution, and page sizes all pass ($stale stale code link(s) in historical briefs, listed above)."
else
  echo "lint: OK — wiki frontmatter, link resolution, and page sizes all pass."
fi
